#!@author Nguyễn Tiến Tài
#!created_at 08/02/2023
#!description: General
# Info Swagger Admin APi
info:
    title: Document Admin
    description: CURD Borrow Book
    version: 1.0.0
servers:
    - url: http://localhost:5000
      description: Local development server admin api
# General
components:
    # Parameter
    parameters:
        X-DEVICE-ID:
            in: header
            name: X-DEVICE-ID
            required: true
            schema:
                type: string
        X-OS-TYPE:
            in: header
            name: X-OS-TYPE
            required: true
            schema:
                type: string
        X-OS-VERSION:
            in: header
            name: X-OS-VERSION
            required: true
            schema:
                type: string
        X-APP-VERSION:
            in: header
            name: X-APP-VERSION
            required: true
            schema:
                type: string
        X-DEVICE-NAME:
            in: header
            name: X-DEVICE-NAME
            required: true
            schema:
                type: string
        TOKEN:
            in: header
            name: Authorization
            type: string
            description: Bearer Token
            required: true
            schema:
                type: bearerToken
    # Unauthorized
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid, or the user does not have access to perform the action,or or Device Invalid
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 400
                            message:
                                type: string
                                example: 'Unauthorized'
        # Fail CURD Fail
        ServerCURDFail:
            description: CURD Fail !!!
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 500
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Internal Server Error
        ServerFail:
            description: Service die
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 503
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Out Of Service

    #!@author Nguyễn Tiến Tài
    #!created_at 04/04/2023
    #!description: Create borrow book
paths:
    /v1/admin/private/borrow_book/create:
        post:
            summary: Create Borrow_book
            tags: [Create Borrow_book]
            operationId: createBorrowBook
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        borrow_book_input:
                                            type: object
                                            properties:
                                                book_id:
                                                    type: string
                                                    example: '1475825111725506562'
                                                user_id:
                                                    type: string
                                                    example: '1475825111725506562'
                        required:
                            - book_id
                            - user_id
            responses:
                200:
                    description: update success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                503:
                    $ref: '#/components/responses/ServerFail'
    #!@author Nguyễn Tiến Tài
    #!created_at 08/03/2023
    #!description: update borrow book
    /v1/admin/private/borrow_book/update:
        post:
            summary: Update Borrow_book
            tags: [Update Borrow_book]
            operationId: updateBorrowBook
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        borrow_book_input:
                                            type: object
                                            properties:
                                                borrowed_book_id:
                                                    type: string
                                                    example: '1475825111725506562'
                                                start_date:
                                                    type: string
                                                    example: '2023-03-08 15:20:00'
                                                due_date:
                                                    type: string
                                                    example: '2023-03-15 15:20:00'
                                                status:
                                                    type: number
                                                    example: 20
                        required:
                            - book_id
                            - user_id
                            - start_date
                            - due_date
                            - status
            responses:
                200:
                    description: update success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                503:
                    $ref: '#/components/responses/ServerFail'

    #!@author Nguyễn Tiến Tài
    #!created_at 09/03/2023
    #!description: Detail Borrowed
    /v1/admin/private/borrow_book/detail/:borrowed_book_id:
        get:
            summary: Detail Borrowed
            tags: [Detail Borrowed]
            operationId: detailBorrowed
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            responses:
                200:
                    description: Detail success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'
    #!@author Nguyễn Tiến Tài
    #!created_at 03/02/2023
    #!description: Get all categories
    /v1/admin/private/borrow_book/all:
        get:
            summary: Get all Borrowed
            tags: [Get all Borrowed]
            operationId: getAllBorrowed
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            responses:
                200:
                    description: success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'
