#!@author Nguyễn Tiến Tài
#!created_at 08/02/2023
#!description: General
# Info Swagger Admin APi
info:
    title: Document Admin
    description: CURD Student
    version: 1.0.0
servers:
    - url: http://localhost:5000
      description: Local development server admin api
# General
components:
    # Parameter
    parameters:
        X-DEVICE-ID:
            in: header
            name: X-DEVICE-ID
            required: true
            schema:
                type: string
        X-OS-TYPE:
            in: header
            name: X-OS-TYPE
            required: true
            schema:
                type: string
        X-OS-VERSION:
            in: header
            name: X-OS-VERSION
            required: true
            schema:
                type: string
        X-APP-VERSION:
            in: header
            name: X-APP-VERSION
            required: true
            schema:
                type: string
        X-DEVICE-NAME:
            in: header
            name: X-DEVICE-NAME
            required: true
            schema:
                type: string
        TOKEN:
            in: header
            name: Authorization
            type: string
            description: Bearer Token
            required: true
            schema:
                type: bearerToken
    # Unauthorized
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid, or the user does not have access to perform the action,or or Device Invalid
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 400
                            message:
                                type: string
                                example: 'Unauthorized'
        # Fail CURD Fail
        ServerCURDFail:
            description: CURD Fail !!!
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 500
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Internal Server Error
        ServerFail:
            description: Service die
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 503
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Out Of Service
    #!@author Nguyễn Tiến Tài
    #!created_at 25/03/2023
    #!description: create student
paths:
    /v1/admin/private/student/create:
        post:
            summary: Create Student
            tags: [Create Student]
            operationId: createStudent
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        create_student_input:
                                            type: object
                                            properties:
                                                name:
                                                    type: string
                                                    example: Tai
                                                mssv:
                                                    type: number
                                                    example: 60136782
                                                phone_number:
                                                    type: string
                                                    example: 0798805764
                                                class_room:
                                                    type: string
                                                    example: 60-CNTT2
                                                email:
                                                    type: string
                                                    example: 60-CNTT2
                                                dob:
                                                    type: number
                                                    example: 20000101
                                                gender:
                                                    type: number
                                                    example: 1
                                                tole:
                                                    type: number
                                                    example: 1
                        required:
                            - name
                            - mssv
                            - email
                            - gender
                            - dob
                            - class_room
                            - phone_number
                            - role
            responses:
                200:
                    description: Create success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                500:
                    description: Add database fail
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    message:
                                        type: string
                                        example: Duplicate and Error unknown
                503:
                    $ref: '#/components/responses/ServerFail'

    #!@author Nguyễn Tiến Tài
    #!created_at 25/03/2023
    #!description: update student
    /v1/admin/private/student/update:
        post:
            summary: Update Student
            tags: [Update Student]
            operationId: updateStudent
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        update_student_input:
                                            type: object
                                            properties:
                                                student_id:
                                                    type: number
                                                    example: 12312312414
                                                name:
                                                    type: string
                                                    example: Tai
                                                mssv:
                                                    type: number
                                                    example: 60136782
                                                phone_number:
                                                    type: string
                                                    example: 0798805764
                                                class_room:
                                                    type: string
                                                    example: 60-CNTT2
                                                email:
                                                    type: string
                                                    example: 60-CNTT2
                                                dob:
                                                    type: number
                                                    example: 20000101
                                                gender:
                                                    type: number
                                                    example: 1
                                                role:
                                                    type: number
                                                    example: 1
                        required:
                            - student_id
                            - name
                            - mssv
                            - email
                            - gender
                            - dob
                            - class_room
                            - phone_number
                            - role
            responses:
                200:
                    description: update success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                500:
                    description: Add database fail
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    message:
                                        type: string
                                        example: Duplicate and Error unknown
                503:
                    $ref: '#/components/responses/ServerFail'

    #!@author Nguyễn Tiến Tài
    #!created_at 25/03/2023
    #!description: delete student
    /v1/admin/private/student/delete:
        post:
            summary: Delete Student
            tags: [Delete Student]
            operationId: deleteStudent
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        student_id:
                                            type: object
                                            properties:
                                                student_id:
                                                    type: string
                                                    example: 1474830717476143106
                        required:
                            - student_id
            responses:
                200:
                    description: Delete success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Bad Request
                500:
                    description: Add database fail
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    message:
                                        type: string
                                        example: Duplicate and Error unknown
                503:
                    $ref: '#/components/responses/ServerFail'

    #!@author Nguyễn Tiến Tài
    #!created_at 25/03/2023
    #!description: detail student
    /v1/admin/private/student/detail/:student_id:
        get:
            summary: Detail Student
            tags: [Detail Student]
            operationId: detailStudent
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            responses:
                200:
                    description: Detail success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'

    #!@author Nguyễn Tiến Tài
    #!created_at 25/03/2023
    #!description: all student
    /v1/admin/private/student/all:
        get:
            summary: Get all Student
            tags: [Get all Student]
            operationId: getAllStudent
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            responses:
                200:
                    description: success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'
