#!@author Nguyễn Tiến Tài
#!created_at 08/02/2023
#!description: General
# Info Swagger User APi
info:
    title: Document Student
    description: CURD FAVORITE
    version: 1.0.0
servers:
    - url: http://localhost:5001
      description: Local development server user api
# General
components:
    # Parameter
    parameters:
        X-DEVICE-ID:
            in: header
            name: X-DEVICE-ID
            required: true
            schema:
                type: string
        X-OS-TYPE:
            in: header
            name: X-OS-TYPE
            required: true
            schema:
                type: string
        X-OS-VERSION:
            in: header
            name: X-OS-VERSION
            required: true
            schema:
                type: string
        X-APP-VERSION:
            in: header
            name: X-APP-VERSION
            required: true
            schema:
                type: string
        X-DEVICE-NAME:
            in: header
            name: X-DEVICE-NAME
            required: true
            schema:
                type: string
        TOKEN:
            in: header
            name: Authorization
            type: string
            description: Bearer Token
            required: true
            schema:
                type: bearerToken
    # Unauthorized
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid, or the user does not have access to perform the action,or or Device Invalid
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 400
                            message:
                                type: string
                                example: 'Unauthorized'
        # Fail CURD Fail
        ServerCURDFail:
            description: CURD Fail !!!
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 500
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Internal Server Error
        ServerFail:
            description: Service die
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 503
                            message:
                                type: string
                                example: Service Unavailable
                            element:
                                type: object
                                example: Out Of Service
paths:
    #!@author Nguyễn Tiến Tài
    #!created_at 04/04/2023
    #!description: CREATE FAVORITE
    /v1/user/private/favorite/create:
        get:
            summary: Detail favorite
            tags: [Detail favorite]
            operationId: detailFavorite
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        favorite_input:
                                            type: object
                                            properties:
                                                book_id:
                                                    type: number
                                                    example: 1486024816199729154
                        required:
                            - book_id
            responses:
                200:
                    description: Detail success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'
    #!@author Nguyễn Tiến Tài
    #!created_at 04/04/2023
    #!description: DEL FAVORITE
    /v1/user/private/favorite/delete:
        get:
            summary: Get all favorite
            tags: [Get all favorite]
            operationId: getAllFavorite
            parameters:
                - $ref: '#/components/parameters/COOKIE-CLIENT'
                - $ref: '#/components/parameters/X-DEVICE-ID'
                - $ref: '#/components/parameters/X-OS-TYPE'
                - $ref: '#/components/parameters/X-OS-VERSION'
                - $ref: '#/components/parameters/X-APP-VERSION'
                - $ref: '#/components/parameters/X-DEVICE-NAME'
                - $ref: '#/components/parameters/TOKEN'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                input:
                                    type: object
                                    properties:
                                        favorite_input:
                                            type: object
                                            properties:
                                                favorite_book_id:
                                                    type: number
                                                    example: 1486024816199729154
                        required:
                            - favorite_book_id
            responses:
                200:
                    description: success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    message:
                                        type: string
                                        example: Success
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    message:
                                        type: string
                                        example: Success
                503:
                    $ref: '#/components/responses/ServerFail'
